name: SonarCloud
on:
  push:

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Sonarqube
        run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"boczv" /o:"bocz_viktor"
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
            /d:sonar.cs.opencover.reportsPaths=coverage.xml
          dotnet build --no-incremental
          coverlet .\CovExample.Tests\bin\Debug\net6.0\CovExample.Tests.dll
            --target "dotnet" 
            --targetargs "test --no-build"
            -f=opencover 
            -o="coverage.xml"
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"